router_id_enable: false
symmetric_routing: false

interface_description_8:
  - "r1-r2"
  - "r2-r1"
  - "r3-r2"
interface_ip_8:
  - "10.0.10.1"
  - "10.0.10.2"
  - "10.0.11.1"
interface_description_9:
  - "r1-r3"
  - "r2-r3"
  - "r3-r1"
interface_ip_9:
  - "10.0.12.1"
  - "10.0.11.2"
  - "10.0.12.2"
interface_description_10:
  - "net1"
  - "net2"
  - "net3"
interface_ip_10:
  - "192.168.10.1"
  - "192.168.20.1"
  - "192.168.30.1"
