---
- name: update apt cache
  apt:
   update_cache=yes
   cache_valid_time=3600

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  ignore_errors: yes
  loop:
    - vim
    - nftables
    - curl
    - wget
    - ca-certificates
    - apt-transport-https
    - unzip
    - net-tools
