---
#/etc/resolv.conf нужен для настройки системы
#разрешения доменных имён (DNS) на всех машинах в сети
#!!!!!!Разный для машин зоны dmz и для остальных
- name: set resolv.conf
  template:
    src: "template/dns/server-resolv.conf.j2"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
