---
#ДНС сервер - собирает машруты всех, через него все попадают в интернет
- name: Развернуть динамическую машрутизацию
  template:
    src: "template/frr/frr_dnsSrv.conf.j2"
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: '0640'
  when: inventory_hostname == 'dnsSrv'

- name: Развернуть динамическую машрутизацию
  template:
    src: "template/frr/frr_dnsSrv.conf.j2"
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: '0640'
  when: inventory_hostname  != 'dnsSrv'

  notify:
    - restart_frr
