---
- name: Validate condition result
  debug:
     msg: "The condition result is {{ var_group }}"
     
- name: Развернуть nftables.conf
  template:
    src: "template/nft/nft_{{ var_group }}.conf.j2"
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0600'
  when: var_group in group_names
  notify:
    - restart_nft
