---
- name: Включить только ospfd
  lineinfile:
    path: /etc/frr/daemons
    # Используем простой поиск по строке — без регулярок
    line: "ospfd=yes"
    insertafter: "^#ospfd="
    backup: yes

- name: Развернуть динамическую машрутизацию на остальных серверах
  template:
    src: "template/frr/frr_cl.conf.j2"
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: '0640'

  notify:
    - start_frr
    - restart_frr
