---
#Включение функции пересылки транзитных пакетов через интерфесы роутеров
#Отключение запрета на симметричный роутинг
- name: set up forward packages across routers
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: 'net.ipv4.conf.all.forwarding', value: '1'}
    - {name: 'net.ipv4.conf.all.rp_filter', value: '0'}
