services:
  database:
    labels:
      com.example.description: "Database mysql"
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    labels:
      com.example.description: "Wordpress"
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network
    depends_on:
      - database

  nginx:
    labels:
      com.example.description: "Nginx"
    image: nginx:latest
    container_name: nginx
    ports:
      - 8083:8083
      - 8081:8081
      - 8082:8082

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - app-network

  app:
    labels:
      com.example.description: "App"
    build: ./python
    container_name: app
    restart: always
    env_file:
      - .env
    command: "gunicorn --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application"
    networks:
      - app-network

  node:
    labels:
      com.example.description: "Node.js"
    image: node:16.13.2-alpine3.15
    container_name: node
    working_dir: /opt/server
    volumes:
      - ./node:/opt/server
    command: node test.js
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
