---
- name: Stop MySQL replication
  community.mysql.mysql_replication:
    login_user: "{{ user_adm }}"
    login_password: "{{ user_adm_password }}"
    mode: stopreplica
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true

- name: Reset MySQL replication
  community.mysql.mysql_replication:
    login_user: "{{ user_adm }}"
    login_password: "{{ user_adm_password }}"
    mode: resetreplicaall
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true

- name: Restart MySQL service
  service:
    name: mysql
    state: restarted
