---
- name: restart_sys
  command: systemctl daemon-reload

- name: start_alert
  systemd:
    name: "alertmanager.service"
    daemon_reload: yes
    enabled: yes
    state: started


- name: start_prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: start_grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes

- name: restart_grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes

- name: start_frr
  systemd:
    name: frr
    enabled: yes
    state: started

- name: restart_frr
  systemd:
    name: frr
    state: restarted

- name: restart_nft
  systemd:
    name: nftables
    enabled: yes
    state: restarted

- name: start_snmp
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  loop:
    - snmp.service
