---
#добавляется скрипт knock port
- name: copy iptables config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "755"
  with_items:
    - { src: "files/knockscript.sh", dest: "/home/vagrant/knockscript.sh"}
