---
#module handlers
- name: start_frr
  systemd:
    name: frr
    enabled: yes
    state: started


- name: restart_frr
  systemd:
    name: frr
    enabled: yes
    state: restarted


- name: restart_nft
  systemd:
    name: nftables
    enabled: yes
    state: restarted
