---
#Установка пакета
- name: Install openvpn
  apt:
    name: openvpn
    state: present
    update_cache: true
  become: true
  loop:
    - openvpn

- name: Install easy-rsa
  apt:
    name:
      - easy-rsa
      - selinux-utils
    state: present
    update_cache: true
  when: inventory_hostname == "server"
  become: true

- name: Create directory
  ansible.builtin.file:
    path: /etc/openvpn/pki
    state: directory
