---
- name: Init Easy-RSA
  ansible.builtin.command:
  args:
    cmd: "/usr/share/easy-rsa/easyrsa init-pki"
    chdir: /etc/openvpn
    stdin: "yes\n"
  become: True
  register: init_pki

- name: Init2 Easy-RSA
  ansible.builtin.command:
  args:
    cmd: "/usr/share/easy-rsa/easyrsa build-ca server nopass"
    chdir: /etc/openvpn
    stdin: "\n"
  ignore_errors: true
  become: True
