---
#module handlers
- name: restart_nft
  systemd:
    name: nftables
    enabled: yes
    state: restarted

- name: restart_frr
  systemd:
    name: frr
    enabled: yes
    state: started
