---
- name: Добавить GPG-ключ Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Добавить репозиторий Grafana
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Установить Grafana
  apt:
    name: grafana
    version: "{{ grafana_version }}"
    state: present

- name: Создать директорию для Grafana
  file:
    path: /etc/grafana
    state: directory
    mode: '0755'

- name: Скопировать конфиг Grafana
  template:
    src: grafana/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    mode: '0644'
    
  notify:
    -start_grafana
