---
- name: install apt
  include_tasks: 1_install.yml

- name: install Prometeus
  include_tasks: 2_prometeis_inst.yml

- name: install Grafana
  include_tasks: 3_grafana_inst.yml

- name: install Alertmanager
  include_tasks: 4_alter_inst.yml
