---
# - name: install apt
#   include_tasks: 1_install.yml
#
# - name: set resolv
#   include_tasks: 2_resolve.yml

- name: set frr
  include_tasks: 3_frr.yml

- name: set nft
  include_tasks: 4_nft_monitor.yml

- name: install Prometeus
  include_tasks: 4_prometeis_inst.yml

- name: install Grafana
  include_tasks: 5_grafana_inst.yml

# - name: install Alertmanager
#   include_tasks: 7_alter_inst.yml
