---
- name: Создать пользователя root@127.0.0.1, если его нет
  mysql_query:
    query: |
      CREATE USER 'root'@'127.0.0.1'IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes

- name: Создать пользователя root@127.0.0.1,
  mysql_query:
    query: |
      GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: yes
