---
- name: update apt cache
  apt:
   update_cache=yes
   cache_valid_time=3600

- name: Install packages
  apt:
    name: "gnupg2"
    state: present
    update_cache: true
  become: true
  ignore_errors: yes

    -
