---
- name: install MySql
  include_tasks: 1_install_mySql.yml

- name: Add password
  include_tasks: 2_add_pass.yml
# #
- name: SEt MySql
  include_tasks: 3_set_dbMySql.yml

- name: Set admin
  import_tasks: 5_set_root.yml

- name: Set db-master
  import_tasks: 6_db_master.yml
  when: inventory_hostname == '{{ name_master }}'

- name: Set WordPress2
  import_tasks: 7_set_dbwordpress.yml

# - name: Drop Slave
#   import_tasks: 0_8_change_master.yml

#репликация двоичного файла журнала на основе позиции
- name: Set slave
  import_tasks: 8_db_slave.yml
  when: inventory_hostname == '{{ name_slave }}'
