---
# - name: install MySql
#   include_tasks: install_mySql.yml
- name: Add password
  include_tasks: add_pass.yml

# - name: Add plugin
#   include_tasks: add_plugin.yml

- name: SEt MySql
  include_tasks: set_dbMySql.yml
