---
#Создание директории для зон
- name: Create dir for my zone
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: '0755'

- name: Конфигурация прямой  и обратной зоны
  template:
    src: "template/dns/{{ item.src }}"
    dest: "/etc/bind/{{ item.dest }}"
    owner: root
    group: bind
    mode: '0644'
  loop:
    - {src: "db.my.linuxpro.j2", dest: "zones/db.my.linuxpro"}
    - {src: "db.ipdns.j2", dest: "zones/db.ipdns"}
    - {src: "named.conf.local.j2", dest: "named.conf.local"}
    - {src: "named.conf.options.j2", dest: "named.conf.options"}

- name: set resolv.conf
  template:
    src: "template/dns/server.conf.j2"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

  notify:
  - restart_bind9
