---
- name: set up ifcfg-bond0
  template:
    src: template/ifcfg-bond0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-bond0
    owner: root
    group: root
    mode: 0644

- name: set up eth1,eth2
  copy:
    src: "{{ item }}"
    dest: /etc/sysconfig/network-scripts/
    owner: root
    group: root
    mode: 0644
  with_items:
    - template/ifcfg-eth1
    - template/ifcfg-eth2


  notify:
    - restart_hosts
