---
#module handlers
#Выключение firewalld
- name: firewalld_stopped
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
#Перезапускаем iptables и включаем автозапуск
- name: iptables_service
  ansible.builtin.service:
    name: iptables
    state: restarted
    enabled: yes
