---
- name: restart_bind9
  systemd:
    name: named
    enabled: yes
    state: restarted

- name: start_angie
  systemd:
    name: angie
    enabled: yes
    state: started

- name: reload_angie
  systemd:
    name: angie
    enabled: yes
    state: reloaded

- name: start_frr
  systemd:
    name: frr
    enabled: yes
    state: started

- name: restart_frr
  systemd:
    name: frr
    enabled: yes
    state: restarted

- name: restart_nft
  systemd:
    name: nftables
    enabled: yes
    state: restarted
