---
#Установка дополнительных пакетов все хосты
- name: dop_install and set sinhronized time
  hosts: ipa_clients
  gather_facts: true
  become: True

  roles:
  - 1_customization

- name: set hosts
  hosts: all
  gather_facts: true
  become: True

  roles:
  - 2_set_hosts

- name: install server freeipa
  hosts: servers
  gather_facts: true
  become: True

  roles:
  - 3_freeipa_server
  tags:
    - ipaset

- name: install client freeipa
  hosts: clients
  gather_facts: true
  become: True

  roles:
  - 4_freeipa_client
  tags:
    - ipaclient
